//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login and Checkout.
        /// </summary>
        internal static string btnLoginAndCheckout_Text {
            get {
                return ResourceManager.GetString("btnLoginAndCheckout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order.
        /// </summary>
        internal static string btnPlaceOrder_Text {
            get {
                return ResourceManager.GetString("btnPlaceOrder.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to Checkout.
        /// </summary>
        internal static string CheckoutOnSite_Text {
            get {
                return ResourceManager.GetString("CheckoutOnSite.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This coupon is not valid, please check back at a later date.
        /// </summary>
        internal static string CouponStatus_ActiveDateInvalidFrom {
            get {
                return ResourceManager.GetString("CouponStatus.ActiveDateInvalidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This coupon has expired.
        /// </summary>
        internal static string CouponStatus_ActiveDateInvalidTo {
            get {
                return ResourceManager.GetString("CouponStatus.ActiveDateInvalidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This coupon has already been applied to your order.
        /// </summary>
        internal static string CouponStatus_AlreadyApplied {
            get {
                return ResourceManager.GetString("CouponStatus.AlreadyApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This coupon has expired from too many uses.
        /// </summary>
        internal static string CouponStatus_ExceededMaxLifetimeRedemptions {
            get {
                return ResourceManager.GetString("CouponStatus.ExceededMaxLifetimeRedemptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not met the minimum order amount for this coupon.
        /// </summary>
        internal static string CouponStatus_MinOrderAmountNotReached {
            get {
                return ResourceManager.GetString("CouponStatus.MinOrderAmountNotReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This coupon does not apply to any products in your order.
        /// </summary>
        internal static string CouponStatus_NoEligibleProduct {
            get {
                return ResourceManager.GetString("CouponStatus.NoEligibleProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This coupon does not apply to your chosen shipping option.
        /// </summary>
        internal static string CouponStatus_NoEligibleShipping {
            get {
                return ResourceManager.GetString("CouponStatus.NoEligibleShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of your existing coupons cannot be combined with any other coupons.
        /// </summary>
        internal static string CouponStatus_NonCombinableCouponAlreadyInUse {
            get {
                return ResourceManager.GetString("CouponStatus.NonCombinableCouponAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This coupon is not active.
        /// </summary>
        internal static string CouponStatus_NotActive {
            get {
                return ResourceManager.GetString("CouponStatus.NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This coupon cannot be combined with any other coupons.
        /// </summary>
        internal static string CouponStatus_NotCombinable {
            get {
                return ResourceManager.GetString("CouponStatus.NotCombinable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This coupon is invalid.
        /// </summary>
        internal static string CouponStatus_NotFound {
            get {
                return ResourceManager.GetString("CouponStatus.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon has been applied to your order.
        /// </summary>
        internal static string CouponStatus_Valid {
            get {
                return ResourceManager.GetString("CouponStatus.Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Notes.
        /// </summary>
        internal static string lblOrderNotes_Text {
            get {
                return ResourceManager.GetString("lblOrderNotes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing &amp;raquo;.
        /// </summary>
        internal static string litBillingBreadcrumb_Text {
            get {
                return ResourceManager.GetString("litBillingBreadcrumb.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Information.
        /// </summary>
        internal static string litBillingInformation_Text {
            get {
                return ResourceManager.GetString("litBillingInformation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill To:.
        /// </summary>
        internal static string litBillTo_Text {
            get {
                return ResourceManager.GetString("litBillTo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cart is currently empty..
        /// </summary>
        internal static string litCartIsEmpty_Text {
            get {
                return ResourceManager.GetString("litCartIsEmpty.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout as a Guest.
        /// </summary>
        internal static string litCheckoutAsAGuest_Text {
            get {
                return ResourceManager.GetString("litCheckoutAsAGuest.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout Complete.
        /// </summary>
        internal static string litCheckoutComplete_Text {
            get {
                return ResourceManager.GetString("litCheckoutComplete.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string litCheckoutHeader_Text {
            get {
                return ResourceManager.GetString("litCheckoutHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout - Login or Continue.
        /// </summary>
        internal static string litCheckoutLoginOrContinue_Text {
            get {
                return ResourceManager.GetString("litCheckoutLoginOrContinue.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order has no shippable items..
        /// </summary>
        internal static string litNoShippableItems_Text {
            get {
                return ResourceManager.GetString("litNoShippableItems.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order #.
        /// </summary>
        internal static string litOrderNumber_Text {
            get {
                return ResourceManager.GetString("litOrderNumber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Receipt.
        /// </summary>
        internal static string litOrderReceipt_Text {
            get {
                return ResourceManager.GetString("litOrderReceipt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been received..
        /// </summary>
        internal static string litOrderReceived_Text {
            get {
                return ResourceManager.GetString("litOrderReceived.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment &amp;raquo;.
        /// </summary>
        internal static string litPaymentBreadcrumb_Text {
            get {
                return ResourceManager.GetString("litPaymentBreadcrumb.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Order Details.
        /// </summary>
        internal static string litPrintOrderDetails_Text {
            get {
                return ResourceManager.GetString("litPrintOrderDetails.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we process your order....
        /// </summary>
        internal static string litProcessingOrder_Text {
            get {
                return ResourceManager.GetString("litProcessingOrder.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Order &amp;raquo;.
        /// </summary>
        internal static string litReviewOrderBreadcrumb_Text {
            get {
                return ResourceManager.GetString("litReviewOrderBreadcrumb.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Order.
        /// </summary>
        internal static string litReviewOrder_Text {
            get {
                return ResourceManager.GetString("litReviewOrder.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping &amp;raquo;.
        /// </summary>
        internal static string litShippingBreadcrumb_Text {
            get {
                return ResourceManager.GetString("litShippingBreadcrumb.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Method &amp;raquo;.
        /// </summary>
        internal static string litShippingMethodBreadcrumb_Text {
            get {
                return ResourceManager.GetString("litShippingMethodBreadcrumb.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Cart.
        /// </summary>
        internal static string litViewCart_Text {
            get {
                return ResourceManager.GetString("litViewCart.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will also receive an order confirmation email with the details of your order..
        /// </summary>
        internal static string litYouWillReceiveAnEmail_Text {
            get {
                return ResourceManager.GetString("litYouWillReceiveAnEmail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        internal static string NameOfCart_Text {
            get {
                return ResourceManager.GetString("NameOfCart.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;siteCredit&quot;&gt;&lt;a href=&quot;http://www.dnnspot.com/Modules/DotNetNuke-Shopping-Cart&quot;&gt;DNN Store Module&lt;/a&gt; by &lt;a href=&quot;http://www.dnnspot.com&quot;&gt;DNNspot&lt;/a&gt;&lt;/span&gt;.
        /// </summary>
        internal static string SiteCredit_Text {
            get {
                return ResourceManager.GetString("SiteCredit.Text", resourceCulture);
            }
        }
    }
}
